=== SedaQ/trainings-java-se3/jprog2-xml/src/main/resources/backups/persons.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="content">
        <xs:annotation>
            <xs:documentation>&lt;content  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="persons.xsd"></xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element name="person">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:byte" name="person_id"/>
                            <xs:element type="xs:string" name="first_name"/>
                            <xs:element type="xs:string" name="last_name"/>
                            <xs:element name="address">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="street"/>
                                        <xs:element type="xs:int" name="zip_code"/>
                                        <xs:element type="xs:byte" name="house_number"/>
                                        <xs:element type="xs:string" name="city"/>
                                        <xs:element type="xs:string" name="country"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="group">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="name"/>
                                        <xs:element name="roles">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element type="xs:string" name="role"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute type="xs:string" name="state"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== SedaQ/trainings-java-se3/jprog2-xml/src/main/resources/xslt/persons.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!--<content  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="persons.xsd"> -->
<content>
    <person state="CZE">
        <person_id>1</person_id>
        <first_name>Pavel</first_name>
        <last_name>Seda</last_name>
        <address>
            <street>XYZ123</street>
            <zip_code>91200</zip_code>
            <house_number>12</house_number>
            <city>Brno</city>
            <country>Czech Republic</country>
        </address>
        <group>
            <name>legends</name>
            <roles>
                <role>CHIEF</role>
            </roles>
        </group>
    </person>
    <person state="ENG">
        <person_id>2</person_id>
        <first_name>Karel</first_name>
        <last_name>Tovaris</last_name>
        <address>
            <street>XYZ123</street>
            <zip_code>91200</zip_code>
            <house_number>12</house_number>
            <city>Brno</city>
            <country>Czech Republic</country>
        </address>
        <group>
            <name>legends</name>
            <roles>
                <role>CHIEF</role>
            </roles>
        </group>
    </person>
    <person state="SVK">
        <person_id>3</person_id>
        <first_name>Anezka</first_name>
        <last_name>Burska</last_name>
        <address>
            <street>XYZ123</street>
            <zip_code>91200</zip_code>
            <house_number>12</house_number>
            <city>Brno</city>
            <country>Czech Republic</country>
        </address>
        <group>
            <name>legends</name>
            <roles>
                <role>EMPLOYEE</role>
            </roles>
        </group>
    </person>
</content>

=== SedaQ/trainings-java-se3/jprog2-xml/src/main/resources/persons.xml
<?xml version="1.0" encoding="UTF-8" ?>
<content  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="persons.xsd">
    <person>
        <person_id state="CZE">1</person_id>
        <first_name>Pavel</first_name>
        <last_name>Seda</last_name>
        <address>
            <street>XYZ123</street>
            <zip_code>91200</zip_code>
            <house_number>12</house_number>
            <city>Brno</city>
            <country>Czech Republic</country>
        </address>
        <group>
            <name>legends</name>
            <roles>
                <role>CHIEF</role>
            </roles>
        </group>
    </person>
</content>
